### ISSUE TITLE
Z-wave plug (Schuko TZWP-100) not updating status.

### ISSUE THREAD

**Issue by lurendrejer** [yhaugom/com.telldus#4] opened 2018-05-29 15:18 UTC
Hi.

I have a ton of the plugs (schuko's) - i've been running them for quite some time, as a basic z-wave device. They have been 100% reliable in regards to updating their status. (On/Off)

I installed the app, tried re-including two plugs - they don't update their status.
Tried two more today - same problem.

Thank you for the app.

**Comment by yhaugom** [comment] 2018-08-20 12:38
Not sure why this doesn´t work. Been really busy lately, so havn´t had the time to look into it. And I don´t have the plug myself, so I cannot test it. Need help to test eventually.

**Comment by yhaugom** [comment] 2019-01-01 10:12
@randirundi do you have a log of the data received by Homey? I have done some changes to the JSON-file to get it to validate with the new athom-cli. It is uploaded to this repository as of now, if you would like to give it a try.

**Comment by randirundi** [comment] 2019-01-02 12:38
@yhaugom Installed 1.0.3 from repository and still same issue. Control from Homey works good but manual change of switches is not reflected in Homey.

Z-wave log looks as follows for the two Telldus Shuko devices I have:
**Manual switch off:**
Node 30
```
[2019-01-02T12:14:00.834Z] Node[30]: Received application command for COMMAND_CLASS_SWITCH_BINARY, data: 0x0300
[2019-01-02T12:14:00.835Z] Node[30]: [COMMAND_CLASS_SWITCH_BINARY] {"Value (Raw)":{"type":"Buffer","data":[0]},"Value":"off/disable"}
[2019-01-02T12:14:00.854Z] Node[30]: Received application command for COMMAND_CLASS_BASIC, data: 0x0100
[2019-01-02T12:14:00.854Z] Node[30]: [COMMAND_CLASS_BASIC] {"Value (Raw)":{"type":"Buffer","data":[0]},"Value":0}
```

Node 31
```
[2019-01-02T12:14:39.138Z] Node[31]: Received application command for COMMAND_CLASS_SWITCH_BINARY, data: 0x0300
[2019-01-02T12:14:39.138Z] Node[31]: [COMMAND_CLASS_SWITCH_BINARY] {"Value (Raw)":{"type":"Buffer","data":[0]},"Value":"off/disable"}
[2019-01-02T12:14:39.202Z] Node[31]: Received application command for COMMAND_CLASS_BASIC, data: 0x0100
[2019-01-02T12:14:39.202Z] Node[31]: [COMMAND_CLASS_BASIC] {"Value (Raw)":{"type":"Buffer","data":[0]},"Value":0}
```

**Manual switch on:**
Node 30
```
[2019-01-02T12:15:11.574Z] Node[30]: Received application command for COMMAND_CLASS_SWITCH_BINARY, data: 0x03ff
[2019-01-02T12:15:11.575Z] Node[30]: [COMMAND_CLASS_SWITCH_BINARY] {"Value (Raw)":{"type":"Buffer","data":[255]},"Value":"on/enable"}
[2019-01-02T12:15:11.596Z] Node[30]: Received application command for COMMAND_CLASS_BASIC, data: 0x01ff
[2019-01-02T12:15:11.596Z] Node[30]: [COMMAND_CLASS_BASIC] {"Value (Raw)":{"type":"Buffer","data":[255]},"Value":255}
```

Node 31
```
[2019-01-02T12:19:25.598Z] Node[31]: Received application command for COMMAND_CLASS_SWITCH_BINARY, data: 0x03ff
[2019-01-02T12:19:25.598Z] Node[31]: [COMMAND_CLASS_SWITCH_BINARY] {"Value (Raw)":{"type":"Buffer","data":[255]},"Value":"on/enable"}
[2019-01-02T12:19:25.661Z] Node[31]: Received application command for COMMAND_CLASS_BASIC, data: 0x01ff
[2019-01-02T12:19:25.662Z] Node[31]: [COMMAND_CLASS_BASIC] {"Value (Raw)":{"type":"Buffer","data":[255]},"Value":255}
```

**Comment by yhaugom** [comment] 2019-01-02 12:42
Thank you!
I will have a look when I have time again!
Yngve

Fra: randirundi <notifications@github.com>
Sendt: 2. januar 2019 13:39
Til: yhaugom/com.telldus <com.telldus@noreply.github.com>
Kopi: Yngve Haugom <yngve_haugom@hotmail.com>; Mention <mention@noreply.github.com>
Emne: Re: [yhaugom/com.telldus] z-wave plug not updating status. (#4)


@yhaugom<https://github.com/yhaugom> Installed 1.0.3 from repository and still same issue. Control from Homey works good but manual change of switches is not reflected in Homey.

Z-wave log looks as follows for the two Telldus Shuko devices I have:
Manual switch off:
Node 30

[2019-01-02T12:14:00.834Z] Node[30]: Received application command for COMMAND_CLASS_SWITCH_BINARY, data: 0x0300

[2019-01-02T12:14:00.835Z] Node[30]: [COMMAND_CLASS_SWITCH_BINARY] {"Value (Raw)":{"type":"Buffer","data":[0]},"Value":"off/disable"}

[2019-01-02T12:14:00.854Z] Node[30]: Received application command for COMMAND_CLASS_BASIC, data: 0x0100

[2019-01-02T12:14:00.854Z] Node[30]: [COMMAND_CLASS_BASIC] {"Value (Raw)":{"type":"Buffer","data":[0]},"Value":0}

Node 31

[2019-01-02T12:14:39.138Z] Node[31]: Received application command for COMMAND_CLASS_SWITCH_BINARY, data: 0x0300

[2019-01-02T12:14:39.138Z] Node[31]: [COMMAND_CLASS_SWITCH_BINARY] {"Value (Raw)":{"type":"Buffer","data":[0]},"Value":"off/disable"}

[2019-01-02T12:14:39.202Z] Node[31]: Received application command for COMMAND_CLASS_BASIC, data: 0x0100

[2019-01-02T12:14:39.202Z] Node[31]: [COMMAND_CLASS_BASIC] {"Value (Raw)":{"type":"Buffer","data":[0]},"Value":0}

Manual switch on:
Node 30

[2019-01-02T12:15:11.574Z] Node[30]: Received application command for COMMAND_CLASS_SWITCH_BINARY, data: 0x03ff

[2019-01-02T12:15:11.575Z] Node[30]: [COMMAND_CLASS_SWITCH_BINARY] {"Value (Raw)":{"type":"Buffer","data":[255]},"Value":"on/enable"}

[2019-01-02T12:15:11.596Z] Node[30]: Received application command for COMMAND_CLASS_BASIC, data: 0x01ff

[2019-01-02T12:15:11.596Z] Node[30]: [COMMAND_CLASS_BASIC] {"Value (Raw)":{"type":"Buffer","data":[255]},"Value":255}

Node 31

[2019-01-02T12:19:25.598Z] Node[31]: Received application command for COMMAND_CLASS_SWITCH_BINARY, data: 0x03ff

[2019-01-02T12:19:25.598Z] Node[31]: [COMMAND_CLASS_SWITCH_BINARY] {"Value (Raw)":{"type":"Buffer","data":[255]},"Value":"on/enable"}

[2019-01-02T12:19:25.661Z] Node[31]: Received application command for COMMAND_CLASS_BASIC, data: 0x01ff

[2019-01-02T12:19:25.662Z] Node[31]: [COMMAND_CLASS_BASIC] {"Value (Raw)":{"type":"Buffer","data":[255]},"Value":255}

**Comment by randirundi** [comment] 2019-01-12 00:37
I saw in a Fibaro example that they register some kind of callback listener like this (in onMeshInit),

// register a report listener
		this.registerReportListener('SWITCH_BINARY', 'SWITCH_BINARY_REPORT', ( rawReport, parsedReport ) => {
			console.log('registerReportListener', rawReport, parsedReport);
		});

Can this be something that is needed?

**Comment by yhaugom** [comment] 2019-01-12 10:47
That should not be necessary. Because it is nothing to parse. Everything seems standard. Should be taken care of allready. I will ask athom support. The report is what is expected in the BASIC.js and SWITCH_BINARY.js

`module.exports = {
	get: 'BASIC_GET',
	set: 'BASIC_SET',
	setParser: value => ({
		'Value': (value) ? 255 : 0,
	}),
	report: 'BASIC_REPORT',
	reportParser(report) {
		if (report && report.hasOwnProperty('Value')) return report.Value > 0;
		return null;
	},
};`

**Comment by yhaugom** [comment] 2019-01-18 23:14
@randirundi could you please provide me with a diagnostics report for the app? Find it under app - settings - create diagnostics report. Then send me the ID for the report please.
It could as well be due to some problems with the Athom core. Other issue with other plugs not updating power readings is probably because of problem with meshdriver. 
Would like to se those reports. Thank you!

**Comment by randirundi** [comment] 2019-01-19 09:20
Had to reinstall from appstore to generate diagnostics report, but I guess the latest version in appstore was same as I installed manually a few weeks ago? Anyhow, id is: 9f61516e-6727-4b7b-b909-0d7c3db9764d

**Comment by yhaugom** [comment] 2019-02-01 14:10
@JohanMarini please contact Athom support regarding this issue. I don't believe it is related to this app. I specifically asked for comments on my last app store submission, but they didn't respond.
I also have similar issues with other devices under other apps. 
Have seen bug fix for "...issue preventing devices from updating in real time" in the most recent beta in testflight. Maybe that will work?

**Comment by yhaugom** [comment] 2019-03-11 10:21
@JohanMarini and @randirundi Do you still have this issue? Are you running the latest Homey firmware?

**Comment by randirundi** [comment] 2019-03-14 19:40
Yes, I am running Homey updated to latest and the issue is still there.

**Comment by JohanMarini** [comment] 2019-03-14 22:58
Hi!
Yes, still the same issue. Both for Telldus and Philio wall plugs. 
Running Homey version 2.0.4

Kindest Regards
Johan

**Comment by kungktd** [comment] 2019-11-05 22:08
I just noticed I too are having the same issue with the plug. The mini plug seems fine though.
Anybody got a solution or any idea how we can solve this?

**Comment by JohanLaCed** [comment] 2019-11-12 05:46
Same issue here as well, not updating in homey when manually triggered.

**Comment by kungktd** [comment] 2019-12-03 13:02
@yhaugom Have you had time to look into this?

**Comment by yhaugom** [comment] 2020-01-03 14:54
Sorry, @kungktd , no I have not yet. I will try this month.

**Comment by kungktd** [comment] 2020-01-03 14:57
Good to hear from you @yhaugom. Let me know if there is something I can do to help out.

**Comment by yhaugom** [comment] 2020-01-14 23:18
@kungktd I think I might have found a solution.
I have a beta version available [here](https://homey.app/a/com.telldus/test/).
I have not been able to test it very much, so please test it on your own risk.
I do not think anything should break.
I tested it myself with magnet sensors and one plug-in switch installed, and none of them stopped working.
Anyone testing this, please let me know how it goes!

**Comment by yhaugom** [comment] 2020-01-14 23:25
Don’t install the beta yet (if someone saw my last post (deleted)). I installed it from the app store, and then my devices broke. Need to have a look at that later.

**Comment by yhaugom** [comment] 2020-01-14 23:31
@kungktd I think I might have found a solution.
I have a beta version available [here](https://homey.app/a/com.telldus/test/).
I have not been able to test it very much, so please test it on your own risk.
I do not think anything should break. 
I tested it myself with magnet sensors and one plug-in switch installed, and none of them stopped working. At first it seemed to break the devices, but reinstalled and it was fine. Maybe I was to impatient.
Anyone testing this, please let me know how it goes!

**Comment by kungktd** [comment] 2020-01-14 23:36
So just to be clear, it’s ok to try the beta? :)

**Comment by kungktd** [comment] 2020-01-15 00:17
I installed the beta and can confirm that it works. The TZWP-100 is not changing states when pushing the button on the device. Great work @yhaugom!
I have also tried the function off the TZWP-102 and that plug is still working as it should.

**Comment by yhaugom** [comment] 2020-01-15 08:41
Ok, great. I will have a closer look at some other small updates and improvements as well, but not until next week. Please let me know if you run into any trouble @kungktd 
Sorry for the major delay to get this working. I went and bought a plug of my own, to better be able to test it.

**Comment by yhaugom** [comment] 2020-01-15 15:38
Closing this, as it will be implemented in next stable if nothing changes.

**Closed by yhaugom** 2020-01-15 15:38 UTC
